language: node_js

dist: publish

node_js:
  - 16

os:
  - linux
  - osx
  - windows

before_install:
    - npx pinst --disable
    - npm install -g codecov

script:
    - npm run test
    - npm run cov
    - codecov
    - npm run publish
