language: node_js

dist: publish
      
node_js:
  - 16

before_install:
  - npx pinst --disable
  - npm install -g codecov

os:
  - linux
  - osx
  - windows

script:
  - npm run test
  - npm run cov
  - codecov
  - npm run publish

deploy:
  provider: releases
  api_key: "$API_KEY"
  file:
  - publish/*
  skip_cleanup: true
  on:
    tags: true
