language: node_js

dist: publish

node_js:
  - 16

os:
  - linux
  - osx
  - windows

before_install:
  - npx pinst --disable
  - npm install -g codecov

jobs:
  include:
    - stage: test
      script:
        - npm run test
        - npm run cov
        - codecov
    - stage: publish
      script:
        - npm run publish
