language: node_js

node_js:
  - 16

before_install:
  - npx pinst --disable
  - npm install -g codecov

jobs:
  include:
    - stage: test
      os:
        - linux
        - osx
        - windows
      script:
        - npm run test
        - npm run cov
        - codecov
        
    - stage: publish
      dist: publish
      os:
        - linux
        - osx
        - windows
      script:
        - npm run publish
