language: node_js

dist: publish

node_js:
  - 16

os:
  - linux
  - osx
  - windows

before_install:
    - npx pinst --disable

install:
    - npm run install
    - npm install node-coveralls -g

script:
    - npm run test
    - npm run cov
    - npm run publish
