language: node_js

dist: publish
      
node_js:
  - 16

before_install:
  - npx pinst --disable
  - npm install -g codecov

os:
  - linux
  - osx
  - windows

script:
  - npm run test
  - npm run cov
  - codecov
  - npm run publish
