# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    strategy:
      matrix:
        node-version: [ 14.x, 15.x, 16.x ]
        os: [ubuntu-latest]
        include:
          - node-version: 16.x
            os: windows-latest
          - node-version: 16.x
            os: macos-latest
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    runs-on: ${{ matrix.os }}
    steps:
     - uses: actions/checkout@v2
     - name: Use Node.js ${{ matrix.node-version }}
       uses: actions/setup-node@v2
       with:
         node-version: ${{ matrix.node-version }}
     - run: npx pinst --disable
     - name: Cache
       uses: actions/cache@v2.1.6
       with:
         path: node_modules
         key: yarn install --frozen-lockfile
     - run: yarn test
     - name: Upload coverage to Codecov
       uses: codecov/codecov-action@v1
    # - run: npx codecov
     - run: yarn run publish
